# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'SonarEndpoint'
    organization: 'v-abadalov'
    scannerMode: 'Other'
    extraProperties: |
      # Additional properties that will be passed to the scanner,
      # Put one key=value per line, example:
      # sonar.exclusions=**/*.bin
      sonar.projectKey=v-abadalov_Tester
      sonar.projectName=Tester

- task: Maven@3
  inputs:
      mavenPomFile: maven-multimodule/pom.xml
      goals: verify
      options: -B -Drevision-suffix=$(Build.BuildNumber)
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      codeCoverageToolOption: 'JaCoCo'
      codeCoverageClassFilesDirectories: "module1, module2"
      codeCoverageSourceDirectories: "module1, module2, tests"
      javaHomeOption: JDKVersion
      jdkVersionOption: '1.11'
      mavenVersionOption: Default
      mavenOptions: -Xmx3072m
      mavenAuthenticateFeed: false
      effectivePomSkip: false
      sonarQubeRunAnalysis: true
      isJacocoCoverageReportXML: true
      sqMavenPluginVersionChoice: 'latest'

- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'
    